server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/phraiz
    username: root
    password: 1234

#  redis:
#    host: ${REDIS_HOST}
#    port: 6379
#    timeout: 5000
#    lettuce:
#      shutdown-timeout: 100
#      pool:
#        max-active: 10
#        max-idle: 5
#        min-idle: 1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    com.phraiz.back: DEBUG
