name: workflow.yml

on:
  push:
    branches:
      - main
      - deploy
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DEV_DB_URL: ${{ secrets.DEV_DB_URL }}
      DEV_DB_USERNAME: ${{ secrets.DEV_DB_USERNAME }}
      DEV_DB_PASSWORD: ${{ secrets.DEV_DB_PASSWORD }}
      GPT_API_KEY: ${{ secrets.GPT_API_KEY }}
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permissions to Gradle wrapper
        run: chmod +x ./gradlew
        shell: bash

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build project with Gradle
        run: ./gradlew build
        shell: bash

      - name: Enable QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@v2

      - name: Configure Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.ref_name == 'deploy' }}
          tags: |
            choeunbin/phraiz:latest
            choeunbin/phraiz:${{ github.sha }}